---

- name: Deploy Alex Smith web site
  hosts: all
  become: yes
  tasks:
    - name: Download the folder 
      get_url:
        url: https://github.com/utrains/static-resume/archive/refs/heads/main.zip 
        dest: /tmp/main.zip
    
    - name: Unzip alex file
      unarchive:
        src: /tmp/main.zip
        dest: /tmp
        remote_src: yes
      when: ansible_os_family=="Debian"
    - name: Install httpd on Redhat family
      yum: 
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"
    - name : Copy content to index
      copy:
        src: /tmp/static-resume-main/
        dest: /var/www/html/
        remote_src: yes
      when: ansible_os_family=="RedHat"
    - name: Start service httpd, if not started doemon
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family=="RedHat"
