---
- hosts: ws
  become: 1
  gather_facts: 1
  ignore_errors: True
  tasks:
     - name: package Install
       yum:
         name: "{{item}}"
         state: present 
       loop:
           - wget
           - finger
           - docker
           - httpd
           - ntp
           - curl      
